apiVersion: v1
kind: Service
metadata:
  name: quoteapi-service
spec:
  selector:
    app: quoteapi
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
